### ISSUE TITLE
我想请教一下为什么我的 cgi 响应之后是这样的o(╥﹏╥)o

### ISSUE THREAD

**Issue by ResurgamTin** [hewei-nju/MyTinyWebServer#1]
![image](https://user-images.githubusercontent.com/101855041/165951030-54cdb2b6-32c5-460d-a273-f4a02e8eba93.png)
linux 安装了 python 解释器的。
求教大佬！

**Comment by WeiHea** [comment]
> ![image](https://user-images.githubusercontent.com/101855041/165951030-54cdb2b6-32c5-460d-a273-f4a02e8eba93.png) linux 安装了 python 解释器的。 求教大佬！

你没有执行 `sudo chomod 755 cig/post.cgi` 这条命令给 cgi 脚本添加可执行权，它会被当成普通文件。

**Comment by ResurgamTin** [comment]
> > ![image](https://user-images.githubusercontent.com/101855041/165951030-54cdb2b6-32c5-460d-a273-f4a02e8eba93.png) linux 安装了 python 解释器的。 求教大佬！
> 
> 你没有执行 `sudo chomod 755 cig/post.cgi` 这条命令给 cgi 脚本添加可执行权，它会被当成普通文件。

哦，我成功了，但是我记得我昨天添加执行权限了的 o(╯□╰)o Thanks♪(･ω･)ﾉ
